# Generated by Django 5.2.12 on 2026-08-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_agent_next_of_kin_phone_alter_agent_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
