# Generated by Django 4.2.7 on 2026-08-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_agent_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('cash', 'Cash'), ('check', 'Check'), ('paystack', 'Paystack')], max_length=20),
        ),
    ]
