# Generated by Django 4.2.7 on 2026-08-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0004_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
