# Generated by Django 4.2.7 on 2026-09-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0006_agentinvitation_alter_agent_groups_delete_clientuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(max_length=50, unique=True)),
                ('airline', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=10)),
                ('destination', models.CharField(max_length=10)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('departure', models.CharField(max_length=100)),
                ('arrival', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('stops', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_score', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('punctuality_score', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('comfort_score', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('transit_score', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('historical_summary', models.TextField(blank=True, null=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('concerns', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
